<div id="dangerousDiv"></div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g="
        crossorigin="anonymous"></script>

<script>

$(document).ready(function() {
    $.get("/Home/Exception",
        function (data) {
            console.log("Got result!");
            console.log(data);
        })
    .fail(function(error) {
        console.log("Got exception.");
        console.log(error);
    });
});

</script>